apiVersion: v1
kind: Service
metadata:
  name: island-arkgame
  labels:
    app: arkgame
spec:
  type: LoadBalancer
  ports:
  - port: 27015
    targetPort: 27015
    protocol: UDP
    name: ark-steam
  - port: 7777
    targetPort: 7777
    protocol: UDP
    name: ark-gameclient
  - port: 7778
    targetPort: 7778
    protocol: UDP
    name: ark-gamerawudpport
  selector:
    app: arkgame
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkgame
  labels:
    app: arkgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arkgame
  template:
    metadata:
      labels:
        app: arkgame
    spec:
      containers:
      - image: coserak/ark-docker
        name: arkgame
        env:
          # Server Parameters
        - name: SESSIONNAME
          value: IslandArkServer.jenit.org
        - name: SERVERMAP
          value: TheIsland
        - name: SERVERPASSWORD
          value: ~
        - name: ADMINPASSWORD
          value: TuckerDinosaurGod
        ports:
          - containerPort: 27015
            protocol: UDP
            name: ark-steams
          - containerPort: 7777
            protocol: UDP
            name: ark-gameclient
          - containerPort: 7778
            protocol: UDP
            name: ark-gamerawudp
        volumeMounts:
        - name: arkgame-persistent-storage
          mountPath: /ark
      volumes:
      - name: arkgame-persistent-storage
        persistentVolumeClaim:
          claimName: arkgame-pv-claim